### ISSUE TITLE
OpenEMR fails to start with missing letsencrypt volume

### ISSUE THREAD

**Issue by jeffcpullen** [RedHatOfficial/openemr-kube#1]
The current container depends on letsencrypt, but that seems unnecessary as OCP provides the TLS edge encryption. I think it would make more sense to remove the letsencrypt dependency.

**Comment by bostrt** [comment]
This is being indirectly addressed in #27. I'll go ahead and close this now.

**Comment by bostrt** [comment]
Er, no close button for me. @jeffcpullen would you mind?

**Comment by jeffcpullen** [comment]
You bet!

**Comment by isimluk** [comment]
> Er, no close button for me. @jeffcpullen would you mind?

Sir, You have invite pending for this repo. Should be some place in your inbox.
