### ISSUE TITLE
Templating usernames and passwords

### ISSUE THREAD

**Issue by bostrt** [RedHatOfficial/openemr-kube#5]
The username and passwords need to be templated in the YAML but afaik there's no common solution across K8s, OCP3, and OCP4. Is supporting all necessary? 

OpenShift 3/4:
- OpenShift Template

Kubernetes/OCP4:
- Kustomize

All Versions:
- Operator? 
- Helm?
- What else am I missing?

**Comment by maorfr** [comment]
I believe the way to handle this will be to consume the credentials from a k8s Secret:
https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

i can submit a PR to handle that if that helps!

**Comment by jeffcpullen** [comment]
I like that this approach still works with both OCP 3 and 4
